@startuml
class solution41{
    void sortTextFile
    +path to get file(file name)
    +path to read file
    +path to write new output(file name)

    void sortTextFile
        -executes sortTextFile

}

@enduml
